### ISSUE TITLE
Add nodes vpc_peer_connection, vpc_ipv4_gateway, alicloud_faas_function  to vpc_graph

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-mod-alicloud-insights#69]
New Table Needed blocked due to issues raised in plugin side:
https://github.com/turbot/steampipe-plugin-alicloud/issues/320
https://github.com/turbot/steampipe-plugin-alicloud/issues/305
https://github.com/turbot/steampipe-plugin-alicloud/issues/306

**Comment by khushboo9024** [comment]
Currently, this item is not a top priority for us, but we may consider adding it in the future. We're closing this issue for now since it's not part of our immediate plans.
