### ISSUE TITLE
Add nodes message_notification_service_queue, message_notification_service_topic, faas_function to alicloud oss graph

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-mod-alicloud-insights#71]
Issue raised in plugin side blocked as new table needed:
https://github.com/turbot/steampipe-plugin-alicloud/issues/310
https://github.com/turbot/steampipe-plugin-alicloud/issues/309

**Comment by khushboo9024** [comment]
Currently, this item is not a top priority for us, but we may consider adding it in the future. We're closing this issue for now since it's not part of our immediate plans.
