### ISSUE TITLE
Add alicloud_alb as a node to vpc, vswitch, ecs_instance graph

### ISSUE THREAD

**Issue by Priyanka-Chatterjee-2000** [turbot/steampipe-mod-alicloud-insights#72]
Issue raised for new table alicloud_application_load_balancer  in the plugin side:
https://github.com/turbot/steampipe-plugin-alicloud/issues/308

**Comment by khushboo9024** [comment]
Currently, this item is not a top priority for us, but we may consider adding it in the future. We're closing this issue for now since it's not part of our immediate plans.
